import { DocumentBuilder } from '@nestjs/swagger'

export default new DocumentBuilder()
    .addBearerAuth()
    .setTitle('The NewTransport CMS API')
    .setDescription('The NewTransport CMS API Specs')
    .setVersion('1.0')
    .addTag('auth', 'Authentication')
    .addTag('user', 'User Management')
    .addTag('category', 'Category Management')
    .addTag('post', 'Post Management')
    .addTag('banner', 'Banner Management')
    .addTag('customer', 'Customer Management')
    .addTag('setting', 'Setting Management')
    .addTag('service', 'Service Management')
    .addTag('pricing-service', 'Pricing Service Management')
    .addTag('bill', 'Bill Management')
    .addTag('domain', 'Domain Management')
    .build()
